version: 2

models:
  - name: transaction_summary
    description: This table has information about a transactions, and the measurements

    columns:
      - name: uuid
        description: This is a unique identifier for a transaction
        tests:
          - unique
          - not_null

      - name: client_name
        description: Customer's name. PII.

      - name: segment_name
        description: Segment. PII.

      - name: corridor_name
        description: Transactions corridor. PII.

      - name: product_name
        description: product transacted

      - name: bank_name
        description: bank used for transaction

      - name: channel_code
        description: the means of transaction (bank,mobile or cash)
        tests:
          - relationships:
              to: ref('dim_channel')
              field: channel_code

      - name: date_actual
        description: Time transacted

      - name: source
        description: Mode of transaction

      - name: revenue
        description: amount gained from transaction

      - name: volume
        description: payin amount
        